# Remember to change all instances of "SwiftStarterApp" to your own project name

plugin 'cocoapods-keys', {
  :project => "SwiftStarterApp",
  :keys => [
    "PasswordClientId",
    "PasswordClientSecret",
    "ClientId",
    "ClientSecret"
  ]}

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SwiftStarterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftStarterApp
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'KeychainSwift', '~> 15.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'SimpleCheckbox'
  pod 'IQKeyboardManagerSwift'
  pod 'Toast-Swift', '~> 5.0.0'

  target 'SwiftStarterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftStarterAppUITests' do
    # Pods for testing
  end

end
